services:
  db:
    image: pgvector/pgvector:pg17
    container_name: postgres-pgvector
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecurepassword
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d vectordb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sourcelearn-backend
    restart: always
    ports:
      - "8082:8082"
    environment:
      - DATABASE_URL=postgresql+psycopg://myuser:mysecurepassword@db:5432/vectordb
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./app:/app/app
    depends_on:
      db:
        condition: service_healthy
    command: ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8082"]

  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"


volumes:
  pgdata: